version: '3.8'
services:
   frontend:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "3001:3000"
      volumes:
         - ./frontend:/app
         - /app/node_modules
   backend:
      build:
         context: ./backend
         dockerfile: Dockerfile
      links:
      - db
      ports:
      - "8001:5000"
   db:
      image: mysql:8.0.28
      ports:
      - "3307:3306"
      environment:
         MYSQL_ROOT_PASSWORD: root
      volumes:
         - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

